using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace YouTube_Desktop.Core.Models.Media
{
    public class VideoCaptionSnippet
    {
        /// <summary>
        /// The url for the caption
        /// </summary>
        public string CaptionUrl { get; set; }
        /// <summary>
        /// If the caption is auto generated
        /// </summary>
        public bool AutoGenerated { get; set; }
        /// <summary>
        /// The caption language
        /// </summary>
        public YoutubeLanguage CaptionLanguage { get; set; }
    }
}